### ISSUE TITLE
Install instructions + client example

### ISSUE THREAD

**Issue by m4b** [vibhavp/emacs-lsp#1]
Hello!

Was wondering if you could provide very basic install example, etc, but also, a client example communicating over stdout would be great, or how to setup something like this. (Primarily interested in using this with rust language server binary which uses stdout)

Thanks, and keep up the good work!

**Comment by vibhavp** [comment]
A client for rls is defined at https://github.com/vibhavp/emacs-lsp/blob/master/lsp-mode.el#L61. However sending textDocument/onChange to rls somehow panics the worker thread (on unwrapping a `None` value), causing `PoisonError` panics on every request sent afterwards. I'm still investigating this issue.

Also, I've added installation instructions to the `README`.

**Comment by m4b** [comment]
Awwwwwesome, thanks!
