### ISSUE TITLE
Add description so we can easily discover package from MELPA

### ISSUE THREAD

**Issue by Trevoke** [vibhavp/emacs-lsp#12]
![image](https://cloud.githubusercontent.com/assets/67913/21612239/6d480696-d19e-11e6-997a-6a6f989df64e.png)

This is unfriendly :/

**Comment by tutysara** [comment]
We have the description in melpa

I see description=Minor mode for interacting with Language Servers for version=20170311.2126

@Trevoke Can you please check and confirm

**Comment by Trevoke** [comment]
You could have a better description of how it works, basically a copy of the readme, in there as well.

Compare with this:

![image](https://cloud.githubusercontent.com/assets/67913/24716714/e6abc282-19fd-11e7-9bec-43e94c519372.png)

**Comment by Trevoke** [comment]
(but yes I do now see a description too!)
