### ISSUE TITLE
if language server crashes/is not started properly, cannot close buffer

### ISSUE THREAD

**Issue by m4b** [vibhavp/emacs-lsp#16]
Will query "Close the language server for this workspace", yes, results in Process Rust Language Server not running, and buffer not closed.

**Comment by vibhavp** [comment]
Does that hang up emacs as well?

**Comment by m4b** [comment]
No doesn't hang emacs, just can't close the buffer with `C-x k` for example

**Comment by vibhavp** [comment]
I've pushed a temporary fix until a better way to manage process lifetime is implemented. Does this fix the issue?
