### ISSUE TITLE
Invalid options for slot range in lsp-diagnostic

### ISSUE THREAD

**Issue by jonves** [vibhavp/emacs-lsp#17]
When trying to use global-lsp-mode with the Rust language server, the mode fails with:
```
Eager macro-expansion failure: (error "Invalid options for slot range in lsp-diagnostic")
Invalid options for slot range in lsp-diagnostic
```

**Comment by vibhavp** [comment]
Are you using the latest version? I cannot replicate this locally

**Comment by jonves** [comment]
Managed to fix it. The problem was that I was using the Emacs 26 release from the development repository. Rolled back to 25.1 and it solved the issue :)

**Comment by vibhavp** [comment]
Turns out this was because of a new check in Emacs 26's cl-defstruct: https://github.com/vibhavp/emacs-lsp/pull/19
