### ISSUE TITLE
Invoking lsp-capabilities produces an error

### ISSUE THREAD

**Issue by ruimams** [vibhavp/emacs-lsp#29]
Hi, I believe I found a bug. After setting up emacs-lsp and the Rust Language Server I invoked the function `lsp-capabilities` and received this error: `Wrong type argument: listp, "Send full contents"`.

Invoking the same function on an `emacs -Q` with `debug-on-error` enabled produces the following output:
```
Debugger entered--Lisp error: (wrong-type-argument listp "Send full contents")
  car("Send full contents")
  (concat ": " (car (cdr (assoc value type))))
  (cond ((listp type) (concat ": " (car (cdr (assoc value type))))))
  (concat desc (cond ((listp type) (concat ": " (car (cdr (assoc value type)))))) "\n")
  (progn (concat desc (cond ((listp type) (concat ": " (car (cdr (assoc value type)))))) "\n"))
  (if (and elem desc type value) (progn (concat desc (cond ((listp type) (concat ": " (car (cdr ...))))) "\n")))
  (let* ((elem (assoc cap lsp--capabilities)) (desc (car (cdr elem))) (type (cdr (cdr elem))) (value (gethash cap (lsp--server-capabilities)))) (if (and elem desc type value) (progn (concat desc (cond ((listp type) (concat ": " (car ...)))) "\n"))))
  lsp--cap-str("textDocumentSync")
  mapconcat(lsp--cap-str ("textDocumentSync" "hoverProvider" "completionProvider" "signatureHelpProvider" "definitionProvider" "referencesProvider" "documentHighlightProvider" "documentSymbolProvider" "workspaceSymbolProvider" "codeActionProvider" "documentFormattingProvider" "documentRangeFormattingProvider" "renameProvider") "")
  (let ((str (mapconcat (function lsp--cap-str) (reverse (hash-table-keys (lsp--server-capabilities))) ""))) (save-current-buffer (set-buffer (get-buffer-create "lsp-capabilities")) (view-mode -1) (erase-buffer) (insert str) (view-mode 1)) (switch-to-buffer "lsp-capabilities"))
  lsp-capabilities()
  funcall-interactively(lsp-capabilities)
  call-interactively(lsp-capabilities record nil)
  command-execute(lsp-capabilities record)
  execute-extended-command(nil "lsp-capabilities" "lsp-ca")
  funcall-interactively(execute-extended-command nil "lsp-capabilities" "lsp-ca")
  call-interactively(execute-extended-command nil nil)
  command-execute(execute-extended-command)
```

I am running GNU Emacs 25.1.1 on Arch Linux.

**Comment by vibhavp** [comment]
Indeed, this seems to be an issue with the structure of the `lsp--capabilities` constant. I'll try pushing fix soon, thanks.

**Comment by ruimams** [comment]
I have been trying to debug this error and I believe that there is a mismatch between selector `cadr` in function `lsp--cap-str` ([here](https://github.com/vibhavp/emacs-lsp/blob/master/lsp-mode.el#L142)) and the data structure used to represent the options of the `"Document sync method"` ([here](https://github.com/vibhavp/emacs-lsp/blob/master/lsp-mode.el#L120-L122)), in the `lsp--capabilities` constant as you said.

I believe this bug was introduced by ecb1d90995ddce47d022245914dc87b77305c211, when it changed the data structure of the "options" from lists to pairs.

Changing the selector from `cadr` to `cdr` fixes the bug here.

Would you be interested in a PR?
