### ISSUE TITLE
lsp-flycheck is rust specific

### ISSUE THREAD

**Issue by mattiasb** [vibhavp/emacs-lsp#33]
I'm trying out lsp-mode with [PyLS](https://github.com/palantir/python-language-server) and activated `lsp-flycheck` with `lsp-flycheck-setup` but it failed since it wanted to run with the Rust checker. 

See [these lines](https://github.com/vibhavp/emacs-lsp/blob/master/lsp-flycheck.el#L62-L63) for why.

**Comment by vibhavp** [comment]
[This line ](https://github.com/vibhavp/emacs-lsp/blob/master/lsp-flycheck.el#L73)seems to be the primary culprit. I'll make the code independent of language mode, thanks.

**Comment by mattiasb** [comment]
Not really. That whole sexp defines a flycheck-checker for rust-mode, so I believe it's actually just L62 that is wrong.

From C-h v `flycheck-checker`:
```
Documentation:
Syntax checker to use for the current buffer.

If unset or nil, automatically select a suitable syntax checker
from ‘flycheck-checkers’ on every syntax check.

If set to a syntax checker only use this syntax checker and never
select one from ‘flycheck-checkers’ automatically.  The syntax
checker is used regardless of whether it is contained in
‘flycheck-checkers’ or ‘flycheck-disabled-checkers’.  If the
syntax checker is unusable in the current buffer an error is
signaled.
```

**Comment by mattiasb** [comment]
Perhaps @fmdkdd could fill us in here?

**Comment by fmdkdd** [comment]
Ah yes, sorry for that.  I only tested it with Rust.  I've just pushed a PR to fix that, but beware I did not test it.  Let me know if that works for you.
