### ISSUE TITLE
how to test/use features

### ISSUE THREAD

**Issue by m4b** [vibhavp/emacs-lsp#5]
Navigating to a rust source file, asks me if i want to start a new language server, Y, language server correctly started, and appears to start an emacs process.

However, I don't see any lsp M-x functions besides `lsp-capabilities`, which states:

```
The server provides file formatting: Yes
The server provides project symbol support: Yes
The server provides file symbol support: Yes
The server provides references support: Yes
The server provides goto definition support: Yes
The server provides completion support: Yes
The server provides hover support: Yes
Document sync method: Send full contents
``` 

so:

1. What do I need to "play" with the language server? For instance, how do i file format? how does hover support work? completion seems to not use my company backend? what is reference support, etc.?
2. is goto-definition same as racer's M-. ? etc., how does this all tie in?
3. might want to add a restart language server in M-x, as well as some other functions, like `M-x lsp-complete-at-point`, `M-x lsp-hover-at-point` for testing/debugging

Thanks, and keep up the good work!

**Comment by vibhavp** [comment]
Hm, I should add some docs for these. Thanks for helping me test this!

**Comment by vibhavp** [comment]
Added some docs on basic functionality

**Comment by m4b** [comment]
Oh, so for rust clients, I assume we now need to disable emacs racer mode? I also noticed some huge pauses when auto completing, I'm not sure what's causing it, will try a better repro

**Comment by vibhavp** [comment]
Yep, racer should be disabled. I'm still investigating whether pauses are because of RLS or just lsp-mode being inefficient.

**Comment by m4b** [comment]
I think this is resolved with latest readme, closing
