### ISSUE TITLE
Emacs hangs

### ISSUE THREAD

**Issue by TatriX** [vibhavp/emacs-lsp#52]
After opening any rust file and answering "yes" to "start server?" question emacs hangs until I press `C-g`. Any ideas?

```
Start a new Language Server for this project? (y or n) y
lsp--stdio-send-sync: Content-Length: 145
Content-Type: application/vscode-jsonrpc; charset=utf-8

{"jsonrpc":"2.0","method":"initialize","params":{"processId":13843,"rootPath":"/home/tatrix/Documents/rust/hello/src/","capabilities":{}},"id":1}
```

**Comment by vibhavp** [comment]
unfortunately, rust support is borked atm. Could you give me the contents of the stderr buffer? Thanks.

**Comment by TatriX** [comment]
```
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Syntax(EOFWhileParsingValue, 2, 143)', /checkout/src/libcore/result.rs:859
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

**Comment by TatriX** [comment]
Also I think stderr buffer should have earmuffs.
```
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Syntax(EOFWhileParsingValue, 2, 147)', /checkout/src/libcore/result.rs:859
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: rls::server::parse_message
   1: rls::server::LsService::handle_message::{{closure}}
   2: std::panicking::try::do_call
   3: __rust_maybe_catch_panic
             at /checkout/src/libpanic_unwind/lib.rs:98
   4: <F as alloc::boxed::FnBox<A>>::call_box
   5: std::sys::imp::thread::Thread::new::thread_start
             at /checkout/src/liballoc/boxed.rs:650
             at /checkout/src/libstd/sys_common/thread.rs:21
             at /checkout/src/libstd/sys/unix/thread.rs:84
   6: start_thread
   7: clone
```

**Comment by vibhavp** [comment]
Could you see if https://github.com/vibhavp/emacs-lsp/commit/6cf4644900424f7ec5816b0746f8774d492d2701 panics too? I've recently added a `Content-Type` header to outgoing messages, and that might be causing issues.

**Comment by TatriX** [comment]
It didn't panic but
```
Unkown method: rustDocument/diagnosticsBegin
Unkown method: rustDocument/diagnosticsEnd
```

**Comment by TatriX** [comment]
I tried removing `Content-Type` without success.

**Comment by vibhavp** [comment]
I've reverted the Content-Type, could you see if rust panics anymore? This seems to be an issue with rls, as other language server work fine...

> Unkown method: rustDocument/diagnosticsBegin
> Unkown method: rustDocument/diagnosticsEnd

Those are rls specific messages for notifying users of diagnostics check. I'll see if I can handle them appropriately.

**Comment by TatriX** [comment]
Yes, no more panic. But still no completion :(

**Comment by vibhavp** [comment]
The `rustDocument/*` messages should be fixed now. rls is also sending the `diagnosticsBegin` notification to every request sent from Emacs, not sure whether it's a bug in Emacs or rls.

**Comment by TatriX** [comment]
Messages are gone. Still no completion though.
Also when emacs restores desktop session it prompts for "starting new server" via gui which can be a problem if I had 300 files to restore as I usually have.

**Comment by vibhavp** [comment]
I'll add an option to remember server preferences. Still, you wouldn't want to use this as your daily driver for rust support, as rls is still having some problems.
