### ISSUE TITLE
can't jump into std

### ISSUE THREAD

**Issue by m4b** [vibhavp/emacs-lsp#7]
I can't seem to jump into `std::io::Cursor` for example.

Previously, racer needed to know about the source directory location; how can I tell lsp-mode the same (assuming I can or need to?)

**Comment by vibhavp** [comment]
You need to build the rust stdlib in to emit IDs that RLS then can use for goto-def: https://github.com/jonathandturner/rls#standard-library-support

**Comment by m4b** [comment]
:] i should read more
